version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  web:
    build: .
    container_name: django_app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=dfjslkfdjoijewoif09u520392i2oiv2vehb9i84253453445ykokfposjdfpo20394256
      - DATABASE_URL=postgres://django_user:django_password@db:5432/django_db
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge
