version: '3'

services:
  web:
    build: ./config
    command: gunicorn config.config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      - SECRET_KEY=sdkjlfsjdflskjdlfsdjflsdflskdf
      - deploy=True
      - DEBUG=True
      - DATABASE_URL=postgres://user:password@db:5432/my_database
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
